version: '3'

services:
  my_service:
    container_name: my_service
    restart: always
    build: ./my_service
    ports:
      - "8000:8000"
      - "80:80"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server
